
server:
  port: 10006


spring:
  application:
    name: eureka-ribbon-hystrix

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  #Об▓ролл─хпои

feign:
  hystrix:
    enable: true